var base64 = require('base-64')
var utf8 = require('utf8')

const encoded = {
  pt: {
    // exportei do premiere e peguei o code do base64 do xml
    code: 'xAEAAAAAAABEMyIRBAAAAE7///9MAAAASABGAAwACAAAAAAAQAA8AAAAAAAAAAAAOAA3ADAALAAoACQAIAAcAAAAGAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAQASAAAAEwAAACMAAAApAAAAEgAAAAAACBBAAAAAGgAAACyPyxBjsyJQCwcmUBA8fTCjf0xQgAAAAFUAAAAAgAAAAIAAAAAAAoACAAAAAAABAAKAAAAAAAAvgEAAAAMAAAAAAAGAAgABAAGAAAABAAAAA0AAABBbmltYXRpb25UeXBlAAAAUv///wAAAABa////AAAAAAEAAAAEAAAADgAAAEFyZXRoYS1SZWd1bGFyAAABAAAADAAAAAgADAAEAAgACAAAAIAAAAA0AAAAMAAYAAAAFAAQAAAADAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAMAAAABgAAAAAAAAAIAAAADAAAAAAAKpCBAAGAAQAAAAAAAoACgAHAAgACQAKAAAAAAAAAAAACgAIAAUABgAHAAoAAAAA8PDwJQAAAGJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmIAAAA=',
    replace: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
  },
  en: {
    // exportei do premiere e peguei o code do base64 do xml
    code: 'qAEAAAAAAABEMyIRBAAAAE7///9MAAAASABGAAwACAAAAAAAQAA8AAAAAAAAAAAAOAA3ADAALAAoACQAIAAcAAAAGAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAQASAAAAEwAAACMAAAAoAAAAEgAAAAAACBBAAAAAGgAAACyPyxBjsyJQCwcmUBA8fTCjf0xQgAAAAFUAAAAAgAAAAIAAAAAAAoACAAAAAAABAAKAAAAAAAAvgEAAAAMAAAAAAAGAAgABAAGAAAABAAAAA0AAABBbmltYXRpb25UeXBlAAAAcv///wAAAAB6////AAAAAAEAAAAEAAAACwAAAEFyZXRoYS1Cb2xkAAEAAAAMAAAACAAMAAQACAAIAAAAbAAAADQAAAAwABAAAAAAAAAAAAAMAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAwAAAAEAAAAAAAAAAYAAAABAAGAAQAAAAAAAoACAAFAAYABwAKAAAAAAAAAAQABAAEAAAAIgAAAGFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWEAAA==',
    replace: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  },
}

function generate(text, ptOrEn) {
  var bytesUtf = base64.decode(encoded[ptOrEn].code)
  // console.log(text)
  const replaced = bytesUtf.replace(encoded[ptOrEn].replace, utf8.encode(text))
  // console.log(replaced)
  // console.log('-------------------')
  const bytes = utf8.encode(replaced)
  // console.log(bytes)
  return base64.encode(replaced)
}
module.exports = generate
// generate('oi é', 'en')
// console.log(generate('oi é', 'en'))
