const teste = {
  mShadowFontMapHash: null,
  mTextParam: {
    mAlignment: 2.0,
    mBackFillColor: 0.0,
    mBackFillOpacity: 0.0,
    mBackFillSize: 0.0,
    mBackFillVisible: false,
    mDefaultRun: [],
    mHeight: 0.0,
    mHindiDigits: false,
    mIndic: false,
    mIsMask: false,
    mIsMaskInverted: false,
    mIsVerticalText: false,
    mLeading: 0.0,
    mLigatures: false,
    mLineCapType: 0.0,
    mLineJoinType: 0.0,
    mMiterLimit: 0.0,
    mNumStrokes: 1.0,
    mRTL: false,
    mShadowAngle: 135.0,
    mShadowBlur: 40.0,
    mShadowColor: 4144959.0,
    mShadowOffset: 7.0,
    mShadowOpacity: 75.0,
    mShadowSize: 0.0,
    mShadowVisible: false,
    mStyleSheet: {
      mAdditionalStrokeColor: [],
      mAdditionalStrokeVisible: [],
      mAdditionalStrokeWidth: [],
      mBaselineOption: { mParamValues: [[0.0, 0.0]] },
      mBaselineShift: { mParamValues: [[0.0, 0.0]] },
      mCapsOption: { mParamValues: [[0.0, 0.0]] },
      mFauxBold: { mParamValues: [[0, false]] },
      mFauxItalic: { mParamValues: [[0, false]] },
      mFillColor: { mParamValues: [[0.0, 16777215.0]] },
      mFillOverStroke: { mParamValues: [[0, true]] },
      mFillVisible: { mParamValues: [[0, true]] },
      mFontName: { mParamValues: [[0, 'Aretha-Regular']] },
      mFontSize: { mParamValues: [[0.0, 60.0]] },
      mKerning: { mParamValues: [[0.0, 0.0]] },
      mStrokeColor: { mParamValues: [[0.0, 0.0]] },
      mStrokeVisible: { mParamValues: [[0, true]] },
      mStrokeWidth: { mParamValues: [[0.0, 10.0]] },
      mText: '\rcade vc',
      mTracking: { mParamValues: [[0.0, 0.0]] },
      mTsumi: { mParamValues: [[0.0, 0.0]] },
      mUnderline: null,
    },
    mTabWidth: 400.0,
    mVerticalAlignment: 0.0,
    mWidth: 0.0,
  },
  mUseLegacyTextBox: false,
  mVersion: 1.0,
}
